import {EtatFactureVo} from "./etat-facture-vo.model";
import {PaiementFacturesVo} from "./paiement-factures-vo.model";
import {OperationComptableVo} from "./operation-comptable-vo.model";
import {FactureItemsVo} from "./facture-items-vo.model";

export class FactureVo {
  serialVersionUID: number;
  serialVersionUIDMin:number;
  serialVersionUIDMax:number;
  id:number;
  reference:string;
  typeFacture:string;
  annee:number;
  anneeMin:number;
  anneeMax:number;
  mois:number;
  moisMin:number;
  moisMax:number;
  trimester:number;
  trimesterMin:number;
  trimesterMax:number;
  totalHt:number;
  totalHtMin:number;
  totalHtMax:number;
  totalTtc:number;
  totalTtcMin:number;
  totalTtcMax:number;
  tva:number;
  totalDebit:number;
  totalCredit:number;
  tvaMin:number;
  tvaMax:number;
  totalPayerHt:number;
  totalPayerHtMin:number;
  totalPayerHtMax:number;
  totalRestantHt:number;
  totalRestantHtMin:number;
  totalRestantHtMax:number;
  dateFacture:Date;
  dateFactureMin:Date;
  dateFactureMax:Date;
  dateSaisie:Date;
  dateSaisieMin:Date;
  dateSaisieMax:Date;
  referenceSociete:string;
  etatFactureVo:EtatFactureVo;
  paiementFacturesVo:PaiementFacturesVo;
  operationComptablesVo:Array<OperationComptableVo>;
  factureItemsVo:FactureItemsVo;
}
